spring.datasource.driverClassName=org.h2.Driver
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.h2.console.enabled=true

spring.datasource.url=jdbc:postgresql://localhost:5432/gym_management_db
spring.datasource.username=postgres
spring.datasource.password=qwerty123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

